- name: Add Neovim PPA to repository
  apt_repository: repo='ppa:neovim-ppa/unstable'

- name: Install Neovim and python dependencies
  apt: pkg={{ item }} state=installed
  with_items:
    - python-pip
    - python-dev
    - python3-dev
    - python3-pip
    - neovim

- name: pre-create neovim config directory.
  file: path=/home/{{username}}/.config/nvim state=directory owner="{{username}}"

- name: Install vim-plug into neovim config directory
  shell: "source .zshrc && curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  become: yes
  become_user: "{{username}}"
  args:
    chdir: /home/{{username}}
    executable: "/usr/bin/zsh"

- name: install configuration file into neovim config directory.
  copy: src=neovim_config dest=/home/{{username}}/.config/nvim/init.vim owner="{{username}}"

- name: Run neovim to install plugins.
  shell: "source .zshrc && nvim +PlugInstall +qall"
  become: yes
  become_user: "{{username}}"
  args:
    chdir: /home/{{username}}
    executable: "/usr/bin/zsh"
