---
- name: Install ZSH from repository
  apt: pkg=zsh state=installed update_cache=true

- name: Create User account with ZSH set as shell
  user: name={{username}} shell=/usr/bin/zsh generate_ssh_key=yes password=unused

- name: Allow user account sudo access sans password
  shell: echo "{{username}} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/99-user-account
  args:
    creates: /etc/sudoers.d/99-user-account

- name: Install Git from repository
  apt: pkg=git state=installed

- name: Install tmux from repository
  apt: pkg=tmux state=installed

- name: Retrieve Oh My Zsh from Git
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/{{username}}/.oh-my-zsh
  become: yes
  become_user: "{{username}}"

- stat: path=l
- name: Add .zshrc to user home
  template: dest=/home/{{username}}/.zshrc src=zshrc.j2
  become: yes
  become_user: "{{username}}"

- name: Create .zsh.d for zsh extensions
  file: path=/home/{{username}}/.zsh.d state=directory owner="{{username}}" group="{{username}}"

- name: Add .tmux.conf to user home
  copy: src=tmux_config dest=/home/{{username}}/.tmux.conf owner="{{username}}" group="{{username}}"

- name: Determine if we have a mapping to Vagrant.
  stat: path=/vagrant
  register: vagrant

- name: Add generated public key to authorized keys
  shell: "cat id_rsa.pub >> authorized_keys"
  args:
    chdir: "/home/{{username}}/.ssh"
    creates: /home/{{username}}/.ssh/authorized_keys
  become: yes
  become_user: "{{username}}"

- name: Copy generated keypair to provisioner (if present)
  fetch: src=/home/{{username}}/.ssh/id_rsa dest=dev_keypair flat=yes
  when: (vagrant.stat.exists == True)
